### PR TITLE
fix: import `runCLI` off default export (fix #65)

### LINKED ISSUE #65: starting test with Jest 25 errors out with: "TypeError: Cannot read property 'runCLI' of undefined"
Tests properly running with gulp-jest and jest version 24, when upgrading jest to 25+ trigger the error in the subject.
is this project abandoned? Last published package was on 2018.
I am using as a workaround the following package instead: https://www.npmjs.com/package/gulp-jest-acierto

### PR DESCRIPTION
**Pull request by jacobq**
I believe this will fix #65 

See also:

* https://github.com/facebook/jest/issues/9512#issuecomment-581835474
* https://github.com/facebook/jest/pull/8874#discussion_r317470364
* https://github.com/stryker-mutator/stryker/issues/1983

### CODE REVIEW

**Comment by jacobq** [comment]
Should also close #61 and #63

**Comment by sallaben** [comment]
Thank you! Hope this pr gets some attention

**Comment by stepheneb** [comment]
@jacobq thanks for temporarily publishing a package I can use until this pull request gets merged.

Running jest tests is working after replacing `gulp-jest: ^4.0.3"` with your package.

My current devDependencies:

```
"devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/preset-env": "^7.12.7",
    "@babel/preset-typescript": "^7.12.7",
    "babel-jest": "^26.6.3",
    "browser-sync": "^2.26.13",
    "esm": "^3.2.25",
    "gulp": "^4.0.2",
    "gulp-jest": "https://registry.npmjs.org/@jacobq/gulp-jest/-/gulp-jest-4.0.3-PR65.tgz",
    "gulp-sass": "^4.1.0",
    "jest": "^26.6.3",
    "jest-cli": "^26.6.3",
    "node-sass": "^5.0.0"
  }
```

**Comment by anthonyray** [comment]
Thanks @jacobq for this P.R. I tested with your temporary package and it works !

**Pull request merged**
